version: "3"

services:
  db:
    container_name: db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app-development
    ports:
      - 3307:3306
    volumes:
      - mysql:/var/lib/mysql
  testdb:
    container_name: testdb
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app-test
    ports:
      - 3306:3306

volumes:
  mysql: